name: Build Lapelo Executable File
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ github.token }}

# https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#multiple-operating-systems-and-architectures
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        node_version:
          - 14
        architecture:
          - x64
    name: Build On：${{ matrix.os }}_${{ matrix.architecture }} - Node ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Clean Install Modules
        run: npm ci --production

      - name: Install pkg Tool
        run: npm i pkg -g

      # https://docs.github.com/en/actions/learn-github-actions/environment-variables#detecting-the-operating-system
      - name: Use pkg To Package On Windows
        if: runner.os == 'Windows'
        run: pkg -t node${{ matrix.node_version }}-windows . --compress GZip

      - name: Use pkg to Package On Linux
        if: runner.os == 'Linux'
        run: pkg -t node${{ matrix.node_version }}-linux . --compress GZip

      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Declare VERSION
        shell: bash
        run: |
          node -e "
            const fs = require('fs');
            const package = require('./package.json');
            fs.writeFileSync('version-number', 'VERSION_NUMBER=v' + package.version);
          "
          cat ./version-number >> $GITHUB_ENV

      - name: Pre-compress
        shell: bash
        run: |
          npm i archiver
          node -e "
            const archiver = require('archiver');
            const fs = require('fs');
            const path = require('path');
            const output = fs.createWriteStream(path.join(__dirname, 'Lapelo-${{ env.VERSION_NUMBER }}_${{ runner.os }}.zip'));
            const archive = archiver('zip', {
              zlib: { level: 9 }
            });
            archive.pipe(output);
            archive.file('./README.md', { name: 'README.md' });
            archive.file('./LICENSE', { name: 'LICENSE' });
            archive.file('./Lapelo.exe', { name: 'Lapelo.exe' });
            archive.file('./Lapelo', { name: 'Lapelo' });
            archive.finalize();
          "

      - name: Get Current Time
        shell: bash
        id: time
        # set-output is deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
        run: echo "now=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lapelo-${{ env.VERSION_NUMBER }}_${{ runner.os }}-${{ steps.time.outputs.now }}
          path: Lapelo-${{ env.VERSION_NUMBER }}_${{ runner.os }}.zip
          if-no-files-found: error
